//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaoDien.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinhVien", Namespace="http://schemas.datacontract.org/2004/07/service")]
    [System.SerializableAttribute()]
    public partial class SinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private giaoDien.Service.Lop LopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiSinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public giaoDien.Service.Lop Lop {
            get {
                return this.LopField;
            }
            set {
                if ((object.ReferenceEquals(this.LopField, value) != true)) {
                    this.LopField = value;
                    this.RaisePropertyChanged("Lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLop {
            get {
                return this.MaLopField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopField, value) != true)) {
                    this.MaLopField = value;
                    this.RaisePropertyChanged("MaLop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSV {
            get {
                return this.MaSVField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSVField, value) != true)) {
                    this.MaSVField = value;
                    this.RaisePropertyChanged("MaSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiSinh {
            get {
                return this.NoiSinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiSinhField, value) != true)) {
                    this.NoiSinhField = value;
                    this.RaisePropertyChanged("NoiSinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lop", Namespace="http://schemas.datacontract.org/2004/07/service")]
    [System.SerializableAttribute()]
    public partial class Lop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private giaoDien.Service.KhoaHoc KhoaHocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLopField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public giaoDien.Service.KhoaHoc KhoaHoc {
            get {
                return this.KhoaHocField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoaHocField, value) != true)) {
                    this.KhoaHocField = value;
                    this.RaisePropertyChanged("KhoaHoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLop {
            get {
                return this.MaLopField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLopField, value) != true)) {
                    this.MaLopField = value;
                    this.RaisePropertyChanged("MaLop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLop {
            get {
                return this.TenLopField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLopField, value) != true)) {
                    this.TenLopField = value;
                    this.RaisePropertyChanged("TenLop");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhoaHoc", Namespace="http://schemas.datacontract.org/2004/07/service")]
    [System.SerializableAttribute()]
    public partial class KhoaHoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private giaoDien.Service.CT_DaoTao CT_DaoTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public giaoDien.Service.CT_DaoTao CT_DaoTao {
            get {
                return this.CT_DaoTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_DaoTaoField, value) != true)) {
                    this.CT_DaoTaoField = value;
                    this.RaisePropertyChanged("CT_DaoTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTDT {
            get {
                return this.MaCTDTField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTDTField, value) != true)) {
                    this.MaCTDTField = value;
                    this.RaisePropertyChanged("MaCTDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKH {
            get {
                return this.TenKHField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKHField, value) != true)) {
                    this.TenKHField = value;
                    this.RaisePropertyChanged("TenKH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CT_DaoTao", Namespace="http://schemas.datacontract.org/2004/07/service")]
    [System.SerializableAttribute()]
    public partial class CT_DaoTao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaCTDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenCTDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaCTDT {
            get {
                return this.MaCTDTField;
            }
            set {
                if ((object.ReferenceEquals(this.MaCTDTField, value) != true)) {
                    this.MaCTDTField = value;
                    this.RaisePropertyChanged("MaCTDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenCTDT {
            get {
                return this.TenCTDTField;
            }
            set {
                if ((object.ReferenceEquals(this.TenCTDTField, value) != true)) {
                    this.TenCTDTField = value;
                    this.RaisePropertyChanged("TenCTDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonHoc", Namespace="http://schemas.datacontract.org/2004/07/service")]
    [System.SerializableAttribute()]
    public partial class MonHoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaMH {
            get {
                return this.MaMHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMHField, value) != true)) {
                    this.MaMHField = value;
                    this.RaisePropertyChanged("MaMH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenMH {
            get {
                return this.TenMHField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMHField, value) != true)) {
                    this.TenMHField = value;
                    this.RaisePropertyChanged("TenMH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthisv", ReplyAction="http://tempuri.org/IService1/hienthisvResponse")]
        giaoDien.Service.SinhVien[] hienthisv();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthisv", ReplyAction="http://tempuri.org/IService1/hienthisvResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.SinhVien[]> hienthisvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthikhoahoc", ReplyAction="http://tempuri.org/IService1/hienthikhoahocResponse")]
        giaoDien.Service.KhoaHoc[] hienthikhoahoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthikhoahoc", ReplyAction="http://tempuri.org/IService1/hienthikhoahocResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc[]> hienthikhoahocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timSv", ReplyAction="http://tempuri.org/IService1/timSvResponse")]
        giaoDien.Service.SinhVien timSv(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timSv", ReplyAction="http://tempuri.org/IService1/timSvResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.SinhVien> timSvAsync(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_sinhvien", ReplyAction="http://tempuri.org/IService1/timma_sinhvienResponse")]
        giaoDien.Service.SinhVien[] timma_sinhvien(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_sinhvien", ReplyAction="http://tempuri.org/IService1/timma_sinhvienResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.SinhVien[]> timma_sinhvienAsync(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_sinhvien", ReplyAction="http://tempuri.org/IService1/add_sinhvienResponse")]
        bool add_sinhvien(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_sinhvien", ReplyAction="http://tempuri.org/IService1/add_sinhvienResponse")]
        System.Threading.Tasks.Task<bool> add_sinhvienAsync(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_sinhvien", ReplyAction="http://tempuri.org/IService1/delete_sinhvienResponse")]
        bool delete_sinhvien(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_sinhvien", ReplyAction="http://tempuri.org/IService1/delete_sinhvienResponse")]
        System.Threading.Tasks.Task<bool> delete_sinhvienAsync(string MaSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_sinhvien", ReplyAction="http://tempuri.org/IService1/update_sinhvienResponse")]
        bool update_sinhvien(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_sinhvien", ReplyAction="http://tempuri.org/IService1/update_sinhvienResponse")]
        System.Threading.Tasks.Task<bool> update_sinhvienAsync(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_khoahoc", ReplyAction="http://tempuri.org/IService1/timma_khoahocResponse")]
        giaoDien.Service.KhoaHoc[] timma_khoahoc(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_khoahoc", ReplyAction="http://tempuri.org/IService1/timma_khoahocResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc[]> timma_khoahocAsync(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timkh", ReplyAction="http://tempuri.org/IService1/timkhResponse")]
        giaoDien.Service.KhoaHoc timkh(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timkh", ReplyAction="http://tempuri.org/IService1/timkhResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc> timkhAsync(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_khoahoc", ReplyAction="http://tempuri.org/IService1/add_khoahocResponse")]
        bool add_khoahoc(string MaKH, string MaCTDT, string TenKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_khoahoc", ReplyAction="http://tempuri.org/IService1/add_khoahocResponse")]
        System.Threading.Tasks.Task<bool> add_khoahocAsync(string MaKH, string MaCTDT, string TenKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_khoahoc", ReplyAction="http://tempuri.org/IService1/update_khoahocResponse")]
        bool update_khoahoc(string MaKH, string MaCTDT, string TenKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_khoahoc", ReplyAction="http://tempuri.org/IService1/update_khoahocResponse")]
        System.Threading.Tasks.Task<bool> update_khoahocAsync(string MaKH, string MaCTDT, string TenKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_khoahoc", ReplyAction="http://tempuri.org/IService1/delete_khoahocResponse")]
        bool delete_khoahoc(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_khoahoc", ReplyAction="http://tempuri.org/IService1/delete_khoahocResponse")]
        System.Threading.Tasks.Task<bool> delete_khoahocAsync(string MaKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthimonhoc", ReplyAction="http://tempuri.org/IService1/hienthimonhocResponse")]
        giaoDien.Service.MonHoc[] hienthimonhoc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthimonhoc", ReplyAction="http://tempuri.org/IService1/hienthimonhocResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.MonHoc[]> hienthimonhocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_monhoc", ReplyAction="http://tempuri.org/IService1/add_monhocResponse")]
        bool add_monhoc(string MaMH, string TenMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_monhoc", ReplyAction="http://tempuri.org/IService1/add_monhocResponse")]
        System.Threading.Tasks.Task<bool> add_monhocAsync(string MaMH, string TenMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_monhoc", ReplyAction="http://tempuri.org/IService1/delete_monhocResponse")]
        bool delete_monhoc(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_monhoc", ReplyAction="http://tempuri.org/IService1/delete_monhocResponse")]
        System.Threading.Tasks.Task<bool> delete_monhocAsync(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_monhoc", ReplyAction="http://tempuri.org/IService1/timma_monhocResponse")]
        giaoDien.Service.MonHoc[] timma_monhoc(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_monhoc", ReplyAction="http://tempuri.org/IService1/timma_monhocResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.MonHoc[]> timma_monhocAsync(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timmh", ReplyAction="http://tempuri.org/IService1/timmhResponse")]
        giaoDien.Service.MonHoc timmh(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timmh", ReplyAction="http://tempuri.org/IService1/timmhResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.MonHoc> timmhAsync(string MaMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_monhoc", ReplyAction="http://tempuri.org/IService1/update_monhocResponse")]
        bool update_monhoc(string MaMH, string TenMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_monhoc", ReplyAction="http://tempuri.org/IService1/update_monhocResponse")]
        System.Threading.Tasks.Task<bool> update_monhocAsync(string MaMH, string TenMH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthilop", ReplyAction="http://tempuri.org/IService1/hienthilopResponse")]
        giaoDien.Service.Lop[] hienthilop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthilop", ReplyAction="http://tempuri.org/IService1/hienthilopResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.Lop[]> hienthilopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_lop", ReplyAction="http://tempuri.org/IService1/add_lopResponse")]
        bool add_lop(string MaLop, string MaKH, string TenLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_lop", ReplyAction="http://tempuri.org/IService1/add_lopResponse")]
        System.Threading.Tasks.Task<bool> add_lopAsync(string MaLop, string MaKH, string TenLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_lop", ReplyAction="http://tempuri.org/IService1/delete_lopResponse")]
        bool delete_lop(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delete_lop", ReplyAction="http://tempuri.org/IService1/delete_lopResponse")]
        System.Threading.Tasks.Task<bool> delete_lopAsync(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_lop", ReplyAction="http://tempuri.org/IService1/timma_lopResponse")]
        giaoDien.Service.Lop[] timma_lop(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timma_lop", ReplyAction="http://tempuri.org/IService1/timma_lopResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.Lop[]> timma_lopAsync(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timlop", ReplyAction="http://tempuri.org/IService1/timlopResponse")]
        giaoDien.Service.Lop timlop(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/timlop", ReplyAction="http://tempuri.org/IService1/timlopResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.Lop> timlopAsync(string MaLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_lop", ReplyAction="http://tempuri.org/IService1/update_lopResponse")]
        bool update_lop(string MaLop, string MaKH, string TenLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_lop", ReplyAction="http://tempuri.org/IService1/update_lopResponse")]
        System.Threading.Tasks.Task<bool> update_lopAsync(string MaLop, string MaKH, string TenLop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthiChuongTrinh", ReplyAction="http://tempuri.org/IService1/hienthiChuongTrinhResponse")]
        giaoDien.Service.CT_DaoTao[] hienthiChuongTrinh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hienthiChuongTrinh", ReplyAction="http://tempuri.org/IService1/hienthiChuongTrinhResponse")]
        System.Threading.Tasks.Task<giaoDien.Service.CT_DaoTao[]> hienthiChuongTrinhAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : giaoDien.Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<giaoDien.Service.IService1>, giaoDien.Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public giaoDien.Service.SinhVien[] hienthisv() {
            return base.Channel.hienthisv();
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.SinhVien[]> hienthisvAsync() {
            return base.Channel.hienthisvAsync();
        }
        
        public giaoDien.Service.KhoaHoc[] hienthikhoahoc() {
            return base.Channel.hienthikhoahoc();
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc[]> hienthikhoahocAsync() {
            return base.Channel.hienthikhoahocAsync();
        }
        
        public giaoDien.Service.SinhVien timSv(string MaSV) {
            return base.Channel.timSv(MaSV);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.SinhVien> timSvAsync(string MaSV) {
            return base.Channel.timSvAsync(MaSV);
        }
        
        public giaoDien.Service.SinhVien[] timma_sinhvien(string MaSV) {
            return base.Channel.timma_sinhvien(MaSV);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.SinhVien[]> timma_sinhvienAsync(string MaSV) {
            return base.Channel.timma_sinhvienAsync(MaSV);
        }
        
        public bool add_sinhvien(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop) {
            return base.Channel.add_sinhvien(MaSV, HoTen, GioiTinh, NgaySinh, NoiSinh, MaLop);
        }
        
        public System.Threading.Tasks.Task<bool> add_sinhvienAsync(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop) {
            return base.Channel.add_sinhvienAsync(MaSV, HoTen, GioiTinh, NgaySinh, NoiSinh, MaLop);
        }
        
        public bool delete_sinhvien(string MaSV) {
            return base.Channel.delete_sinhvien(MaSV);
        }
        
        public System.Threading.Tasks.Task<bool> delete_sinhvienAsync(string MaSV) {
            return base.Channel.delete_sinhvienAsync(MaSV);
        }
        
        public bool update_sinhvien(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop) {
            return base.Channel.update_sinhvien(MaSV, HoTen, GioiTinh, NgaySinh, NoiSinh, MaLop);
        }
        
        public System.Threading.Tasks.Task<bool> update_sinhvienAsync(string MaSV, string HoTen, string GioiTinh, string NgaySinh, string NoiSinh, string MaLop) {
            return base.Channel.update_sinhvienAsync(MaSV, HoTen, GioiTinh, NgaySinh, NoiSinh, MaLop);
        }
        
        public giaoDien.Service.KhoaHoc[] timma_khoahoc(string MaKH) {
            return base.Channel.timma_khoahoc(MaKH);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc[]> timma_khoahocAsync(string MaKH) {
            return base.Channel.timma_khoahocAsync(MaKH);
        }
        
        public giaoDien.Service.KhoaHoc timkh(string MaKH) {
            return base.Channel.timkh(MaKH);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.KhoaHoc> timkhAsync(string MaKH) {
            return base.Channel.timkhAsync(MaKH);
        }
        
        public bool add_khoahoc(string MaKH, string MaCTDT, string TenKH) {
            return base.Channel.add_khoahoc(MaKH, MaCTDT, TenKH);
        }
        
        public System.Threading.Tasks.Task<bool> add_khoahocAsync(string MaKH, string MaCTDT, string TenKH) {
            return base.Channel.add_khoahocAsync(MaKH, MaCTDT, TenKH);
        }
        
        public bool update_khoahoc(string MaKH, string MaCTDT, string TenKH) {
            return base.Channel.update_khoahoc(MaKH, MaCTDT, TenKH);
        }
        
        public System.Threading.Tasks.Task<bool> update_khoahocAsync(string MaKH, string MaCTDT, string TenKH) {
            return base.Channel.update_khoahocAsync(MaKH, MaCTDT, TenKH);
        }
        
        public bool delete_khoahoc(string MaKH) {
            return base.Channel.delete_khoahoc(MaKH);
        }
        
        public System.Threading.Tasks.Task<bool> delete_khoahocAsync(string MaKH) {
            return base.Channel.delete_khoahocAsync(MaKH);
        }
        
        public giaoDien.Service.MonHoc[] hienthimonhoc() {
            return base.Channel.hienthimonhoc();
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.MonHoc[]> hienthimonhocAsync() {
            return base.Channel.hienthimonhocAsync();
        }
        
        public bool add_monhoc(string MaMH, string TenMH) {
            return base.Channel.add_monhoc(MaMH, TenMH);
        }
        
        public System.Threading.Tasks.Task<bool> add_monhocAsync(string MaMH, string TenMH) {
            return base.Channel.add_monhocAsync(MaMH, TenMH);
        }
        
        public bool delete_monhoc(string MaMH) {
            return base.Channel.delete_monhoc(MaMH);
        }
        
        public System.Threading.Tasks.Task<bool> delete_monhocAsync(string MaMH) {
            return base.Channel.delete_monhocAsync(MaMH);
        }
        
        public giaoDien.Service.MonHoc[] timma_monhoc(string MaMH) {
            return base.Channel.timma_monhoc(MaMH);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.MonHoc[]> timma_monhocAsync(string MaMH) {
            return base.Channel.timma_monhocAsync(MaMH);
        }
        
        public giaoDien.Service.MonHoc timmh(string MaMH) {
            return base.Channel.timmh(MaMH);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.MonHoc> timmhAsync(string MaMH) {
            return base.Channel.timmhAsync(MaMH);
        }
        
        public bool update_monhoc(string MaMH, string TenMH) {
            return base.Channel.update_monhoc(MaMH, TenMH);
        }
        
        public System.Threading.Tasks.Task<bool> update_monhocAsync(string MaMH, string TenMH) {
            return base.Channel.update_monhocAsync(MaMH, TenMH);
        }
        
        public giaoDien.Service.Lop[] hienthilop() {
            return base.Channel.hienthilop();
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.Lop[]> hienthilopAsync() {
            return base.Channel.hienthilopAsync();
        }
        
        public bool add_lop(string MaLop, string MaKH, string TenLop) {
            return base.Channel.add_lop(MaLop, MaKH, TenLop);
        }
        
        public System.Threading.Tasks.Task<bool> add_lopAsync(string MaLop, string MaKH, string TenLop) {
            return base.Channel.add_lopAsync(MaLop, MaKH, TenLop);
        }
        
        public bool delete_lop(string MaLop) {
            return base.Channel.delete_lop(MaLop);
        }
        
        public System.Threading.Tasks.Task<bool> delete_lopAsync(string MaLop) {
            return base.Channel.delete_lopAsync(MaLop);
        }
        
        public giaoDien.Service.Lop[] timma_lop(string MaLop) {
            return base.Channel.timma_lop(MaLop);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.Lop[]> timma_lopAsync(string MaLop) {
            return base.Channel.timma_lopAsync(MaLop);
        }
        
        public giaoDien.Service.Lop timlop(string MaLop) {
            return base.Channel.timlop(MaLop);
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.Lop> timlopAsync(string MaLop) {
            return base.Channel.timlopAsync(MaLop);
        }
        
        public bool update_lop(string MaLop, string MaKH, string TenLop) {
            return base.Channel.update_lop(MaLop, MaKH, TenLop);
        }
        
        public System.Threading.Tasks.Task<bool> update_lopAsync(string MaLop, string MaKH, string TenLop) {
            return base.Channel.update_lopAsync(MaLop, MaKH, TenLop);
        }
        
        public giaoDien.Service.CT_DaoTao[] hienthiChuongTrinh() {
            return base.Channel.hienthiChuongTrinh();
        }
        
        public System.Threading.Tasks.Task<giaoDien.Service.CT_DaoTao[]> hienthiChuongTrinhAsync() {
            return base.Channel.hienthiChuongTrinhAsync();
        }
    }
}
